export type KnifeAsset = { name: string; id: string };
export type SkinAsset = { name: string; path: string; team: "T" | "CT" };
export type SoundEvent = { path: string };
export type WeaponSpeed = { name: string; speed: number };

export class GameAssets {
    static readonly knifes = {
        Bayonet: { name: "Bayonet", id: "500" },
        ButterflyKnife: { name: "Butterfly Knife", id: "515" },
        Karambit: { name: "Karambit", id: "507" },
        M9Bayonet: { name: "M9 Bayonet", id: "508" },
        SkeletonKnife: { name: "Skeleton Knife", id: "525" },
        TalonKnife: { name: "Talon Knife", id: "523" },
        ClassicKnife: { name: "Classic Knife", id: "503" },
        StilettoKnife: { name: "Stiletto Knife", id: "522" },
        FlipKnife: { name: "Flip Knife", id: "505" },
        UrsusKnife: { name: "Ursus Knife", id: "519" },
        ParacordKnife: { name: "Paracord Knife", id: "517" },
        SurvivalKnife: { name: "Survival Knife", id: "518" },
        HuntsmanKnife: { name: "Huntsman Knife", id: "509" },
        FalchionKnife: { name: "Falchion Knife", id: "512" },
        BowieKnife: { name: "Bowie Knife", id: "514" },
        ShadowDaggers: { name: "Shadow Daggers", id: "516" },
        GutKnife: { name: "Gut Knife", id: "506" },
        NavajaKnife: { name: "Navaja Knife", id: "520" },
        NomadKnife: { name: "Nomad Knife", id: "521" },
        KukriKnife: { name: "Kukri Knife", id: "526" },
    } as const satisfies Record<string, KnifeAsset>;

    static readonly customSkins = {
        TheEliteMrMuhlik: { name: "The Elite Mr. Muhlik | Elite Crew", path: "characters/models/tm_leet/tm_leet_variantf.vmdl", team: "T" },
        ProfShahmat: { name: "Prof. Shahmat | Elite Crew", path: "characters/models/tm_leet/tm_leet_varianti.vmdl", team: "T" },
        Osiris: { name: "Osiris | Elite Crew", path: "characters/models/tm_leet/tm_leet_varianth.vmdl", team: "T" },
        GroundRebel: { name: "Ground Rebel | Elite Crew", path: "characters/models/tm_leet/tm_leet_variantg.vmdl", team: "T" },
        JungleRebel: { name: "Jungle Rebel | Elite Crew", path: "characters/models/tm_leet/tm_leet_variantj.vmdl", team: "T" },
        SpecialAgentAva: { name: "Special Agent Ava | FBI", path: "characters/models/ctm_fbi/ctm_fbi_variantb.vmdl", team: "CT" },
        MichaelSyfers: { name: "Michael Syfers | FBI Sniper", path: "characters/models/ctm_fbi/ctm_fbi_varianth.vmdl", team: "CT" },
        MarkusDelrow: { name: "Markus Delrow | FBI HRT", path: "characters/models/ctm_fbi/ctm_fbi_variantg.vmdl", team: "CT" },
        Operator: { name: "Operator | FBI SWAT", path: "characters/models/ctm_fbi/ctm_fbi_variantf.vmdl", team: "CT" },
        SealTeam6Soldier: { name: "Seal Team 6 Soldier | NSWC SEAL", path: "characters/models/ctm_st6/ctm_st6_variante.vmdl", team: "CT" },
        TwoTimesMcCoy: { name: "'Two Times' McCoy | USAF TACP", path: "characters/models/ctm_st6/ctm_st6_variantm.vmdl", team: "CT" },
        Buckshot: { name: "Buckshot | NSWC SEAL", path: "characters/models/ctm_st6/ctm_st6_variantg.vmdl", team: "CT" },
        ThirdCommandoCompany: { name: "3rd Commando Company | KSK", path: "characters/models/ctm_st6/ctm_st6_variantk.vmdl", team: "CT" },
        LtCommanderRicksaw: { name: "Lt. Commander Ricksaw | NSWC SEAL", path: "characters/models/ctm_st6/ctm_st6_varianti.vmdl", team: "CT" },
        BlueberriesBuckshot: { name: "'Blueberries' Buckshot | NSWC SEAL", path: "characters/models/ctm_st6/ctm_st6_variantj.vmdl", team: "CT" },
        TwoTimesMcCoyCavalry: { name: "'Two Times' McCoy | TACP Cavalry", path: "characters/models/ctm_st6/ctm_st6_variantl.vmdl", team: "CT" },
        PrimeiroTenente: { name: "Primeiro Tenente | Brazilian 1st Battalion", path: "characters/models/ctm_st6/ctm_st6_variantn.vmdl", team: "CT" },
        CmdrMaeDeadColdJamison: { name: "Cmdr. Mae 'Dead Cold' Jamison | SWAT", path: "characters/models/ctm_swat/ctm_swat_variante.vmdl", team: "CT" },
        FirstLieutenantFarlow: { name: "1st Lieutenant Farlow | SWAT", path: "characters/models/ctm_swat/ctm_swat_variantf.vmdl", team: "CT" },
        JohnVanHealenKask: { name: "John 'Van Healen' Kask | SWAT", path: "characters/models/ctm_swat/ctm_swat_variantg.vmdl", team: "CT" },
        BioHazSpecialist: { name: "Bio-Haz Specialist | SWAT", path: "characters/models/ctm_swat/ctm_swat_varianth.vmdl", team: "CT" },
        SergeantBombson: { name: "Sergeant Bombson | SWAT", path: "characters/models/ctm_swat/ctm_swat_varianti.vmdl", team: "CT" },
        ChemHazSpecialist: { name: "Chem-Haz Specialist | SWAT", path: "characters/models/ctm_swat/ctm_swat_variantj.vmdl", team: "CT" },
        LieutenantTreeHuggerFarlow: { name: "Lieutenant 'Tree Hugger' Farlow | SWAT", path: "characters/models/ctm_swat/ctm_swat_variantk.vmdl", team: "CT" },
        Maximus: { name: "Maximus | Sabre", path: "characters/models/tm_balkan/tm_balkan_varianti.vmdl", team: "T" },
        Dragomir: { name: "Dragomir | Sabre", path: "characters/models/tm_balkan/tm_balkan_variantf.vmdl", team: "T" },
        TheDoctorRomanov: { name: "'The Doctor' Romanov | Sabre", path: "characters/models/tm_balkan/tm_balkan_varianth.vmdl", team: "T" },
        RezanTheReady: { name: "Rezan The Ready | Sabre", path: "characters/models/tm_balkan/tm_balkan_variantg.vmdl", team: "T" },
        Blackwolf: { name: "Blackwolf | Sabre", path: "characters/models/tm_balkan/tm_balkan_variantj.vmdl", team: "T" },
        RezanTheRedshirt: { name: "Rezan the Redshirt | Sabre", path: "characters/models/tm_balkan/tm_balkan_variantk.vmdl", team: "T" },
        DragomirFootsoldier: { name: "Dragomir | Sabre Footsoldier", path: "characters/models/tm_balkan/tm_balkan_variantl.vmdl", team: "T" },
        BSquadronOfficer: { name: "B Squadron Officer | SAS", path: "characters/models/ctm_sas/ctm_sas_variantf.vmdl", team: "CT" },
        DSquadronOfficer: { name: "D Squadron Officer | NZSAS", path: "characters/models/ctm_sas/ctm_sas_variantg.vmdl", team: "CT" },
        SoldierPhoenix: { name: "Soldier | Phoenix", path: "characters/models/tm_phoenix/tm_phoenix_varianth.vmdl", team: "T" },
        EnforcerPhoenix: { name: "Enforcer | Phoenix", path: "characters/models/tm_phoenix/tm_phoenix_variantf.vmdl", team: "T" },
        Slingshot: { name: "Slingshot | Phoenix", path: "characters/models/tm_phoenix/tm_phoenix_variantg.vmdl", team: "T" },
        StreetSoldier: { name: "Street Soldier | Phoenix", path: "characters/models/tm_phoenix/tm_phoenix_varianti.vmdl", team: "T" },
        SirBloodyMiamiDarryl: { name: "Sir Bloody Miami Darryl | The Professionals", path: "characters/models/tm_professional/tm_professional_varf.vmdl", team: "T" },
        SirBloodySilentDarryl: { name: "Sir Bloody Silent Darryl | The Professionals", path: "characters/models/tm_professional/tm_professional_varf1.vmdl", team: "T" },
        SirBloodySkullheadDarryl: { name: "Sir Bloody Skullhead Darryl | The Professionals", path: "characters/models/tm_professional/tm_professional_varf2.vmdl", team: "T" },
        SirBloodyDarrylRoyale: { name: "Sir Bloody Darryl Royale | The Professionals", path: "characters/models/tm_professional/tm_professional_varf3.vmdl", team: "T" },
        SirBloodyLoudmouthDarryl: { name: "Sir Bloody Loudmouth Darryl | The Professionals", path: "characters/models/tm_professional/tm_professional_varf4.vmdl", team: "T" },
        BloodyDarrylTheStrapped: { name: "Bloody Darryl The Strapped | The Professionals", path: "characters/models/tm_professional/tm_professional_varf5.vmdl", team: "T" },
        SafecrackerVoltzmann: { name: "Safecracker Voltzmann | The Professionals", path: "characters/models/tm_professional/tm_professional_varg.vmdl", team: "T" },
        LittleKev: { name: "Little Kev | The Professionals", path: "characters/models/tm_professional/tm_professional_varh.vmdl", team: "T" },
        NumberK: { name: "Number K | The Professionals", path: "characters/models/tm_professional/tm_professional_vari.vmdl", team: "T" },
        GetawaySally: { name: "Getaway Sally | The Professionals", path: "characters/models/tm_professional/tm_professional_varj.vmdl", team: "T" },
        SousLieutenantMedic: { name: "Sous-Lieutenant Medic | Gendarmerie Nationale", path: "characters/models/ctm_gendarmerie/ctm_gendarmerie_varianta.vmdl", team: "CT" },
        ChemHazCapitaine: { name: "Chem-Haz Capitaine | Gendarmerie Nationale", path: "characters/models/ctm_gendarmerie/ctm_gendarmerie_variantb.vmdl", team: "CT" },
        ChefDEscadronRouchard: { name: "Chef d'Escadron Rouchard | Gendarmerie Nationale", path: "characters/models/ctm_gendarmerie/ctm_gendarmerie_variantc.vmdl", team: "CT" },
        Aspirant: { name: "Aspirant | Gendarmerie Nationale", path: "characters/models/ctm_gendarmerie/ctm_gendarmerie_variantd.vmdl", team: "CT" },
        OfficerJacquesBeltram: { name: "Officer Jacques Beltram | Gendarmerie Nationale", path: "characters/models/ctm_gendarmerie/ctm_gendarmerie_variante.vmdl", team: "CT" },
        CmdrDavidaGogglesFernandez: { name: "Cmdr. Davida 'Goggles' Fernandez | SEAL Frogman", path: "characters/models/ctm_diver/ctm_diver_varianta.vmdl", team: "CT" },
        CmdrFrankWetSoxBaroud: { name: "Cmdr. Frank 'Wet Sox' Baroud | SEAL Frogman", path: "characters/models/ctm_diver/ctm_diver_variantb.vmdl", team: "CT" },
        LieutenantRexKrikey: { name: "Lieutenant Rex Krikey | SEAL Frogman", path: "characters/models/ctm_diver/ctm_diver_variantc.vmdl", team: "CT" },
        EliteTrapperSolman: { name: "Elite Trapper Solman | Guerrilla Warfare", path: "characters/models/tm_jungle_raider/tm_jungle_raider_varianta.vmdl", team: "T" },
        CrasswaterTheForgotten: { name: "Crasswater The Forgotten | Guerrilla Warfare", path: "characters/models/tm_jungle_raider/tm_jungle_raider_variantb.vmdl", team: "T" },
        MediumRareCrasswater: { name: "'Medium Rare' Crasswater | Guerrilla Warfare", path: "characters/models/tm_jungle_raider/tm_jungle_raider_variantb2.vmdl", team: "T" },
        ArnoTheOvergrown: { name: "Arno The Overgrown | Guerrilla Warfare", path: "characters/models/tm_jungle_raider/tm_jungle_raider_variantc.vmdl", team: "T" },
        ColMangosDabisi: { name: "Col. Mangos Dabisi | Guerrilla Warfare", path: "characters/models/tm_jungle_raider/tm_jungle_raider_variantd.vmdl", team: "T" },
        VypaSistaOfTheRevolution: { name: "Vypa Sista of the Revolution | Guerrilla Warfare", path: "characters/models/tm_jungle_raider/tm_jungle_raider_variante.vmdl", team: "T" },
        TrapperAggressor: { name: "Trapper Aggressor | Guerrilla Warfare", path: "characters/models/tm_jungle_raider/tm_jungle_raider_variantf.vmdl", team: "T" },
        Trapper: { name: "Trapper | Guerrilla Warfare", path: "characters/models/tm_jungle_raider/tm_jungle_raider_variantf2.vmdl", team: "T" },
    } as const satisfies Record<string, SkinAsset>;

    static readonly soundEvents = {
        CSGO_beepclear: { path: "csgo.beepclear" },
        CSGO_bell1: { path: "csgo.bell1" },
        CSGO_blip1: { path: "csgo.blip1" },
        CSGO_blip2: { path: "csgo.blip2" },
        CSGO_bugreporter_succeeded: { path: "csgo.bugreporter_succeeded" },
        CSGO_button3: { path: "csgo.button3" },
        CSGO_button9: { path: "csgo.button9" },
        CSGO_button10: { path: "csgo.button10" },
        CSGO_button14: { path: "csgo.button14" },
        CSGO_button2: { path: "csgo.button2" },
        CSGO_weapon_cant_buy: { path: "csgo.weapon_cant_buy" },
        CSGO_weapon_confirm: { path: "csgo.weapon_confirm" },
        Mission_Complete: { path: "UI.Mission.Complete" },
        Mission_Progress: { path: "UI.Mission.QuotaUp" },
        Beep01: { path: "Alert.WarmupTimeoutBeep" },
        Beep_Kill: { path: "UI.ArmsRace.Kill1" },
        Beep_Bomb: { path: "coop.c4_beep_normal" },
        Beep_Bomb_Loud: { path: "coop.c4_beep_loud" },
        Beep_Ping: { path: "UI.PlayerPingUrgent" },
        Beep_Click: { path: "UI.XP.Remaining" },
        Beep_Click2: { path: "UIPanorama.container_countdown" },
        Explosion01: { path: "BaseGrenade.Explode" },
        Explosion02: { path: "c4.explode" },
        Explosion03: { path: "coop_compound.big_explode" },
        Explosion04: { path: "tr.C4Explode" },
        Impact_Ball: { path: "Ball.BulletImpact" },
        Impact_Ball2: { path: "Rubber.BulletImpact" },
        Impact_Baloon: { path: "Balloon.Pop" },
        Impact_Glass: { path: "Bounce.Glass" },
        Impact_Metal: { path: "Bounce.Metal" },
        Impact_Metal2: { path: "Metal_Box.BulletImpact" },
        Impact_Metal3: { path: "MetalVehicle.BulletImpact" },
        Impact_Metal_Barrel: { path: "MetalBarrel.BulletImpact" },
        Impact_Concrete: { path: "Bounce.Shrapnel" },
        Impact_Concrete2: { path: "Concrete.BulletImpact" },
        Impact_Wood: { path: "Bounce.Wood" },
        Impact_Wood2: { path: "Default.BulletImpact" },
        Impact_Cardboard: { path: "Cardboard.BulletImpact" },
        Impact_Carpet: { path: "Carpet.BulletImpact" },
        Impact_Ceiling: { path: "ceiling_tile.BulletImpact" },
        Impact_Chain: { path: "Chain.BulletImpact" },
        Impact_ChainLink: { path: "ChainLink.BulletImpact" },
        Impact_Dirt: { path: "Dirt.BulletImpact" },
        Impact_DryWall: { path: "drywall.BulletImpact" },
        Impact_Soda: { path: "ItemSoda.Bounce" },
        Bounce_Shell: { path: "Bounce.Shell" },
        Bounce_ShotgunShell: { path: "Bounce.ShotgunShell" },
        Pickup: { path: "BaseCombatCharacter.AmmoPickup" },
        yippi: { path: "psp1g.yippie" },
        laugh: { path: "fire2k.laugh" },
        requestMove: { path: "swat_fem.request_move_" },
        ticker: { path: "UIPanorama.XP.Ticker" },
        equitMusicKit: { path: "UIPanorama.equip_musicKit" },
    } as const satisfies Record<string, SoundEvent>;

    static readonly WeaponSpeeds = {
        weapon_glock: { name: "weapon_glock", speed: 240.00 },
        weapon_usp_silencer: { name: "weapon_usp_silencer", speed: 240.00 },
        weapon_hkp2000: { name: "weapon_hkp2000", speed: 240.00 },
        weapon_elite: { name: "weapon_elite", speed: 240.00 },
        weapon_p250: { name: "weapon_p250", speed: 240.00 },
        weapon_fiveseven: { name: "weapon_fiveseven", speed: 240.00 },
        weapon_cz75a: { name: "weapon_cz75a", speed: 240.00 },
        weapon_deagle: { name: "weapon_deagle", speed: 230.00 },
        weapon_revolver: { name: "weapon_revolver", speed: 220.00 },
        weapon_nova: { name: "weapon_nova", speed: 220.00 },
        weapon_xm1014: { name: "weapon_xm1014", speed: 215.00 },
        weapon_sawedoff: { name: "weapon_sawedoff", speed: 210.00 },
        weapon_mag7: { name: "weapon_mag7", speed: 225.00 },
        weapon_m249: { name: "weapon_m249", speed: 195.00 },
        weapon_negev: { name: "weapon_negev", speed: 150.00 },
        weapon_mac10: { name: "weapon_mac10", speed: 240.00 },
        weapon_mp7: { name: "weapon_mp7", speed: 220.00 },
        weapon_mp9: { name: "weapon_mp9", speed: 240.00 },
        weapon_mp5sd: { name: "weapon_mp5sd", speed: 235.00 },
        weapon_ump45: { name: "weapon_ump45", speed: 230.00 },
        weapon_p90: { name: "weapon_p90", speed: 230.00 },
        weapon_bizon: { name: "weapon_bizon", speed: 240.00 },
        weapon_galilar: { name: "weapon_galilar", speed: 215.00 },
        weapon_famas: { name: "weapon_famas", speed: 220.00 },
        weapon_ak47: { name: "weapon_ak47", speed: 215.00 },
        weapon_m4a4: { name: "weapon_m4a4", speed: 225.00 },
        weapon_m4a1_silencer: { name: "weapon_m4a1_silencer", speed: 225.00 },
        weapon_ssg08: { name: "weapon_ssg08", speed: 230.00 },
        weapon_sg556: { name: "weapon_sg556", speed: 210.00 },
        weapon_aug: { name: "weapon_aug", speed: 220.00 },
        weapon_awp: { name: "weapon_awp", speed: 200.00 },
        weapon_g3sg1: { name: "weapon_g3sg1", speed: 215.00 },
        weapon_scar20: { name: "weapon_scar20", speed: 215.00 },
        weapon_molotov: { name: "weapon_molotov", speed: 245.00 },
        weapon_incgrenade: { name: "weapon_incgrenade", speed: 245.00 },
        weapon_decoy: { name: "weapon_decoy", speed: 245.00 },
        weapon_flashbang: { name: "weapon_flashbang", speed: 245.00 },
        weapon_hegrenade: { name: "weapon_hegrenade", speed: 245.00 },
        weapon_smokegrenade: { name: "weapon_smokegrenade", speed: 245.00 },
        weapon_taser: { name: "weapon_taser", speed: 245.00 },
        item_healthshot: { name: "item_healthshot", speed: 250.00 },
        weapon_knife_t: { name: "weapon_knife_t", speed: 250.00 },
        weapon_knife: { name: "weapon_knife", speed: 250.00 },
        weapon_c4: { name: "weapon_c4", speed: 250.00 },
        no_knife: { name: "no_knife", speed: 260.00 },
    } as const satisfies Record<string, WeaponSpeed>;
}